# Generated by Django 3.0.8 on 2020-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comententario',
            name='clasePredecida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comententario',
            name='probabiliad',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
